name: Test FastAPI App

on:
  pull_request:
    branches:
      - main  # Executa os testes sempre que houver um PR na branch main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸš€ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: ğŸ“¦ Instalar DependÃªncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: âœ… Rodar Testes com Pytest
        run: |
          pytest --disable-warnings --maxfail=1
